# Generated by Django 5.1.4 on 2025-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_cartproduct_user_favoriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество товара'),
        ),
    ]
