# Generated by Django 5.1.4 on 2026-02-16 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cartproduct_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'author')},
        ),
    ]
