# Generated by Django 5.1.4 on 2026-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_anonymouscart_cartproduct_anonymous_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfavorite',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
