# Generated by Django 5.1.4 on 2026-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_anonymousfavorite_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouscart',
            options={'verbose_name': 'Корзина (неавторизованный пользователь)', 'verbose_name_plural': 'Корзины (неавторизованные пользователи)'},
        ),
        migrations.AlterModelOptions(
            name='anonymousfavorite',
            options={'verbose_name': 'Избранный товар (неавторизованные пользователи)', 'verbose_name_plural': 'Избранные товары (неавторизованные пользователи)'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный товар', 'verbose_name_plural': 'Избранные товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
    ]
